spring.application.name=student-service
server.port=8080
#spring.cloud.config.enabled=true
#spring.config.import=configserver:http://localhost:8888

#spring.r2dbc.url=r2dbc:mysql://sql102.infinityfree.com:3306/if0_40228713_user_profile?sslMode=DISABLED
spring.r2dbc.url=r2dbc:mysql://localhost:3306/studentdb?sslMode=DISABLED
spring.r2dbc.username=root
spring.r2dbc.password=${dev_pass:NewPassword@123}

