apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: ocirsecret   # must be created with kubectl create secret docker-registry
      containers:
        - name: user-service
          image: hyd.ocir.io/ax9deyw9wgup/ayatullamiddya99/docker-image-registry:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_R2DBC_URL
              value: "r2dbc:mysql://mysql-88a7d1-ayatullamiddya99-2fef.e.aivencloud.com:21734/studentdb?sslMode=DISABLED"
            - name: SPRING_R2DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: aiven-mysql-credentials
                  key: AIVEN_USERNAME
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aiven-mysql-credentials
                  key: AIVEN_PASSWORD
