CREATE TABLE IF NOT EXISTS user_profile (
    email VARCHAR(100) PRIMARY KEY,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    department VARCHAR(100),
    gender VARCHAR(10),
    coursename VARCHAR(100)
);

INSERT INTO user_profile (email, firstname, lastname, department, gender, coursename) VALUES
('student1@example.com', 'John', 'Doe', 'Computer Science', 'Male', 'Java Programming'),
('student2@example.com', 'Jane', 'Smith', 'Electronics', 'Female', 'Digital Systems'),
('student3@example.com', 'Alice', 'Brown', 'Mechanical', 'Female', 'Thermodynamics'),
('student4@example.com', 'Bob', 'Johnson', 'Civil', 'Male', 'Structural Analysis'),
('student5@example.com', 'Charlie', 'Davis', 'Computer Science', 'Male', 'Python Programming'),
('student6@example.com', 'Eve', 'Miller', 'Electronics', 'Female', 'Circuit Design'),
('student7@example.com', 'Frank', 'Wilson', 'Mechanical', 'Male', 'Fluid Mechanics'),
('student8@example.com', 'Grace', 'Moore', 'Civil', 'Female', 'Surveying'),
('student9@example.com', 'Hank', 'Taylor', 'Computer Science', 'Male', 'Data Structures'),
('student10@example.com', 'Ivy', 'Anderson', 'Electronics', 'Female', 'Microcontrollers'),
('student11@example.com', 'Jack', 'Thomas', 'Mechanical', 'Male', 'Machine Design'),
('student12@example.com', 'Kathy', 'Jackson', 'Civil', 'Female', 'Concrete Technology'),
('student13@example.com', 'Leo', 'White', 'Computer Science', 'Male', 'Algorithms'),
('student14@example.com', 'Mia', 'Harris', 'Electronics', 'Female', 'Embedded Systems'),
('student15@example.com', 'Nate', 'Martin', 'Mechanical', 'Male', 'Thermal Engineering'),
('student16@example.com', 'Olivia', 'Thompson', 'Civil', 'Female', 'Geotechnical Engineering'),
('student17@example.com', 'Paul', 'Garcia', 'Computer Science', 'Male', 'Operating Systems'),
('student18@example.com', 'Quinn', 'Martinez', 'Electronics', 'Female', 'Signal Processing'),
('student19@example.com', 'Ray', 'Robinson', 'Mechanical', 'Male', 'Dynamics'),
('student20@example.com', 'Sara', 'Clark', 'Civil', 'Female', 'Hydraulics'),
('student21@example.com', 'Tom', 'Rodriguez', 'Computer Science', 'Male', 'Database Systems'),
('student22@example.com', 'Uma', 'Lewis', 'Electronics', 'Female', 'Power Electronics'),
('student23@example.com', 'Victor', 'Lee', 'Mechanical', 'Male', 'Manufacturing Processes'),
('student24@example.com', 'Wendy', 'Walker', 'Civil', 'Female', 'Transportation Engineering'),
('student25@example.com', 'Xander', 'Hall', 'Computer Science', 'Male', 'Web Development'),
('student26@example.com', 'Yara', 'Allen', 'Electronics', 'Female', 'Communication Systems'),
('student27@example.com', 'Zack', 'Young', 'Mechanical', 'Male', 'Robotics'),
('student28@example.com', 'Amy', 'King', 'Civil', 'Female', 'Structural Design'),
('student29@example.com', 'Brian', 'Wright', 'Computer Science', 'Male', 'Machine Learning'),
('student30@example.com', 'Clara', 'Scott', 'Electronics', 'Female', 'Digital Electronics');