name: Build and Deploy

on:
  push:
    branches:
      - main
      - master
      - development

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # 1. Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Build Spring Boot application
      - name: Build application
        run: mvn clean package -DskipTests

      # 3. Generate unique image tag
      - name: Generate image tag
        shell: pwsh
        run: |
          $IMAGE_TAG = "${{ github.sha }}".Substring(0, 7)
          "IMAGE_TAG=$IMAGE_TAG" >> $env:GITHUB_ENV
          "IMAGE_NAME=hyd.ocir.io/ax9deyw9wgup/ayatullamiddya99/docker-image-registry:$IMAGE_TAG" >> $env:GITHUB_ENV

      # 4. Login to OCIR
      - name: Login to OCIR
        shell: pwsh
        run: |
          $token = "${{ secrets.OCIR_AUTH_TOKEN }}"
          $token | docker login hyd.ocir.io --username "ax9deyw9wgup/ayatullamiddya99@gmail.com" --password-stdin

      # 5. Build and push to OCIR
      - name: Build and push to OCIR
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .
          docker push ${{ env.IMAGE_NAME }}

      # 6. Prepare Deployment YAML
      - name: Prepare Deployment
        shell: pwsh
        run: |
          $deploymentFile = "k8s/deployment.yml"
          $generatedFile = Join-Path $env:RUNNER_TEMP "user-service-deployment.yml"
          $content = Get-Content $deploymentFile -Raw
          $content = $content -replace 'image:\s*.*', "image: $env:IMAGE_NAME"
          Set-Content -Path $generatedFile -Value $content -Encoding UTF8
          "GENERATED_DEPLOYMENT=$generatedFile" >> $env:GITHUB_ENV

      # 7. Apply Deployment
      - name: Deploy new version
        run: |
          kubectl apply -f "$env:GENERATED_DEPLOYMENT"

      # 8. Deploy Service
      - name: Deploy Service
        run: |
          kubectl apply -f k8s/service.yml

      # 9. Deploy Ingress
      - name: Deploy Ingress
        run: |
          kubectl apply -f k8s/ingress.yml

      # 10. Final deployment check
      - name: Final deployment check
        run: |
          kubectl get deployment user-service
          kubectl get pods -l app=user-service -o wide
          kubectl get service user-service
          kubectl get ingress user-service-ingress
